baseurl = "http://www.gitbus.io"
title = "Guges"
author = "Gogs"
copyright = "Copyright (c) 20015 - 2016, Gogs; all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-uno"

[params]
    name = "Guges"
    description = "This is a test static html website for Guges."
    github = "guges"
